from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    HomeView,
    CarsListView,
    ListingsListView,
    MessagesInboxView,
    TestDrivesView,
    SellStartView,
    UserSignupView,
    AccountSettingsView,
    BuyersListView,
    SellersListView,
    LogoutViewCustom,
    ListingUpdateView,
    ListingDeleteView,
    ListingCreateView,
    ListingDetailView,
    ListingMessageView,
    PurchaseListingView,
    UserLoginView,
    CarUpdateView,
    CarDeleteView,
    BuyerDetailView,
    SellerDetailView,
    RequestSellToSellerView,
    RequestBuyToBuyerView,
    TestDriveCreateView,
    TestDriveUpdateView,
    CitiesIndexView,
    CityShowroomsView,
    UpcomingArrivalCreateView,
    ActivityTodosView,
    ActivityMeetingView,
    ActivityHistoryView,
    EmailStatusView,
    InspectionCreateView,
)

urlpatterns = [
    path("", HomeView, name="home"),
    path("cars/", CarsListView, name="cars"),
    path("cars/<str:vin>/edit/", CarUpdateView, name="car_edit"),
    path("cars/<str:vin>/delete/", CarDeleteView, name="car_delete"),
    path("listings/", ListingsListView, name="listings"),
    path("listings/<uuid:listing_id>/", ListingDetailView, name="listing_detail"),
    path("listings/<uuid:listing_id>/message/", ListingMessageView, name="listing_message"),
    path("listings/<uuid:listing_id>/purchase/", PurchaseListingView, name="listing_purchase"),
    path("listings/new/", ListingCreateView, name="listing_new"),
    path("listings/<uuid:listing_id>/edit/", ListingUpdateView, name="listing_edit"),
    path("listings/<uuid:listing_id>/delete/", ListingDeleteView, name="listing_delete"),
    path("messages/", MessagesInboxView, name="messages"),
    path("testdrives/", TestDrivesView, name="testdrives"),
    path("testdrives/new/", TestDriveCreateView, name="testdrive_new"),
    path("testdrives/<uuid:test_drive_id>/edit/", TestDriveUpdateView, name="testdrive_edit"),
    path("cities/", CitiesIndexView, name="cities"),
    path("cities/<slug:city_slug>/", CityShowroomsView, name="city_showrooms"),
    path("cities/arrivals/new/", UpcomingArrivalCreateView, name="arrival_new"),
    path("sell/", SellStartView, name="sell"),
    path("contact/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/contact.html"), name="contact"),
    path("faq/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/faq.html"), name="faq"),
    path("privacy/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/privacy.html"), name="privacy"),
    path("terms/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/terms.html"), name="terms"),
    path("profiles/buyers/", BuyersListView, name="buyers"),
    path("profiles/buyers/<uuid:user_id>/", BuyerDetailView, name="buyers_detail"),
    path("profiles/buyers/<uuid:user_id>/request-buy/", RequestBuyToBuyerView, name="buyer_request_buy"),
    path("profiles/sellers/", SellersListView, name="sellers"),
    path("profiles/sellers/<uuid:user_id>/", SellerDetailView, name="sellers_detail"),
    path("profiles/sellers/<uuid:user_id>/request-sell/", RequestSellToSellerView, name="seller_request_sell"),
    path("signup/", UserSignupView, name="signup"),
    path("login/", UserLoginView, name="login"),
    path("logout/", LogoutViewCustom, name="logout"),
    path("account/settings/", AccountSettingsView, name="account_settings"),
    path("activity/todos/", ActivityTodosView, name="activity_todos"),
    path("activity/meeting/", ActivityMeetingView, name="activity_meeting"),
    path("activity/history/", ActivityHistoryView, name="activity_history"),
    path("email/status/", EmailStatusView, name="email_status"),
    path("inspections/new/", InspectionCreateView, name="inspection_new"),
]
